module.exports = {
  STATUS_CODE_SUCCESS: 200,
  STATUS_CODE_CREATED: 201,
  STATUS_CODE_ERROR: 400,
  STATUS_CODE_UNAUTHORIZE: 401,
  STATUS_CODE_FORBIDDEN: 403,
  STATUS_CODE_INTERNAL: 500,

  MESSAGE_FAILED: "FAILED",
  MESSAGE_SUCCESS: "SUCCESS",

  MESSAGE_RESPONSE_FALIED: "Có lỗi. Vui lòng thử lại.",
  MESSAGE_RESPONSE_SUCCESS: "Thành công",

  REGEX_EMAIL: /\S+@\S+\.\S+/,
};
